# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istolethis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='over',
            field=models.BooleanField(default=False),
        ),
    ]
